// Copyright 2026 Adhish Thite
// SPDX-License-Identifier: Apache-2.0

import AVFoundation
import AppKit
import AudioToolbox
import Carbon
import CoreAudio
import Foundation
import IOKit
import Network
import SQLite3

struct TextInjector {
  // Marker types so clipboard managers (Paste, Maccy, Raycast Clipboard History, ...) skip
  // archiving ephemeral dictation text - org.nspasteboard.org convention.
  private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
  private static let autoGeneratedType = NSPasteboard.PasteboardType(
    "org.nspasteboard.AutoGeneratedType")

  private static let mutationLock = NSLock()
  private static let restorationLock = NSLock()
  private static var pendingRestoration: (version: Int, contents: [NSPasteboardItem])?
  private static let preparation = ClipboardPreparation<[NSPasteboardItem]>(
    version: { NSPasteboard.general.changeCount },
    read: { snapshotClipboard() }
  )

  static func prepareClipboard() { preparation.prepare() }
  static func discardPreparedClipboard() { preparation.discard() }
  static func awaitPreparedClipboard(timeout: Double = 0.15, completion: @escaping (Bool) -> Void) {
    preparation.awaitPrepared(timeout: timeout, completion: completion)
  }

  private static func snapshotClipboard() -> [NSPasteboardItem]? {
    let pb = NSPasteboard.general
    let count = pb.changeCount
    restorationLock.lock()
    let pending = pendingRestoration
    restorationLock.unlock()
    // Consecutive turns must preserve the user's original clipboard, not our temporary text.
    if let pending = pending, pending.version == count { return pending.contents }
    guard let items = pb.pasteboardItems else { return [] }
    var copiedItems: [NSPasteboardItem] = []
    for item in items {
      let newItem = NSPasteboardItem()
      for type in item.types {
        guard let data = item.data(forType: type), newItem.setData(data, forType: type) else {
          return nil
        }
      }
      copiedItems.append(newItem)
    }
    return copiedItems
  }

  private static func restoreClipboard(_ savedItems: [NSPasteboardItem]) {
    let pb = NSPasteboard.general
    pb.clearContents()
    if !savedItems.isEmpty {
      pb.writeObjects(savedItems)
    }
  }

  static func inject(
    text: String, restorePreviousClipboard: Bool = true, completionSound: Bool = true,
    appendSpace: Bool = false, shouldDispatch: () -> Bool = { true }
  ) -> InjectionResult {
    let start = ProcessInfo.processInfo.systemUptime
    func result(_ outcome: Outcome) -> InjectionResult {
      InjectionResult(
        outcome: outcome, latencyMs: (ProcessInfo.processInfo.systemUptime - start) * 1000)
    }
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return result(.failed) }
    let payload = appendSpace ? trimmed + " " : trimmed
    let source = CGEventSource(stateID: .hidSystemState)
    guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true),
      let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false)
    else {
      return result(.failed)
    }
    keyDown.flags = .maskCommand
    keyUp.flags = .maskCommand
    let item = NSPasteboardItem()
    guard item.setString(payload, forType: .string),
      item.setData(Data(), forType: transientType),
      item.setData(Data(), forType: autoGeneratedType)
    else { return result(.failed) }
    let previous = restorePreviousClipboard ? preparation.take() : nil
    guard !restorePreviousClipboard || previous != nil else { return result(.clipboardUnavailable) }
    let pb = NSPasteboard.general
    // Recheck after the caller's focus check: it may need a main-thread hop.
    guard shouldDispatch() else { return result(.dispatchCancelled) }
    mutationLock.lock()
    if let previous = previous, pb.changeCount != previous.version {
      mutationLock.unlock()
      return result(.clipboardUnavailable)
    }
    pb.clearContents()
    let clearedCount = pb.changeCount
    guard pb.writeObjects([item]) else {
      if let previous = previous, pb.changeCount == clearedCount {
        restoreClipboard(previous.contents)
      }
      mutationLock.unlock()
      return result(.failed)
    }
    let ourChangeCount = pb.changeCount
    // This reports event dispatch, not confirmation that the destination consumed the text.
    keyDown.post(tap: .cghidEventTap)
    usleep(10_000)
    keyUp.post(tap: .cghidEventTap)
    if let previous = previous {
      restorationLock.lock()
      pendingRestoration = (ourChangeCount, previous.contents)
      restorationLock.unlock()
      DispatchQueue.global().asyncAfter(
        deadline: .now() + restoreDelay(forPayloadLength: payload.count)
      ) {
        mutationLock.lock()
        if NSPasteboard.general.changeCount == ourChangeCount {
          restoreClipboard(previous.contents)
        }
        mutationLock.unlock()
        restorationLock.lock()
        if pendingRestoration?.version == ourChangeCount { pendingRestoration = nil }
        restorationLock.unlock()
      }
    }
    mutationLock.unlock()
    if completionSound { SoundManager.playCommitSound() }
    return result(.dispatched)
  }

  /// How long the pasted text stays on the clipboard before the previous contents go back.
  /// A slow destination reads a big payload more slowly, and restoring before it has read
  /// the text pastes the old clipboard instead (audit F27), so the wait grows with the
  /// payload: 1 s plus 1 ms per character, capped at 3 s (reached at 2,000 characters).
  static func restoreDelay(forPayloadLength length: Int) -> Double {
    min(3.0, 1.0 + Double(max(0, length)) * 0.001)
  }

  /// Puts text on the clipboard WITHOUT synthesizing ⌘V or restoring the previous clipboard -
  /// the copy-only fallback for secure-input and mid-turn focus changes, so the text stays put
  /// for the user to paste manually.
  static func copyOnly(text: String, appendSpace: Bool = false) -> Bool {
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return false }
    let payload = appendSpace ? trimmed + " " : trimmed
    let item = NSPasteboardItem()
    guard item.setString(payload, forType: .string),
      item.setData(Data(), forType: transientType),
      item.setData(Data(), forType: autoGeneratedType)
    else { return false }
    let pasteboard = NSPasteboard.general
    mutationLock.lock()
    defer { mutationLock.unlock() }
    pasteboard.clearContents()
    return pasteboard.writeObjects([item])
  }
}
